version: '3.8'
services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--save 60 1000
    volumes:
      - redis_data:/data
    command: redis-stack-server --appendonly yes

volumes:
  redis_data: